// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QualityControl.WPF.DB;

#nullable disable

namespace QualityControl.WPF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613123800_RevertErrorCodeToString")]
    partial class RevertErrorCodeToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("QualityControl.WPF.DB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedControllers")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BCAVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ElapsedTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("File_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("License_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Model_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperationCode_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Project_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportType_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResultType_Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UTC_DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("VIN_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WUVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("File_Id");

                    b.HasIndex("License_Id");

                    b.HasIndex("Model_Id");

                    b.HasIndex("OperationCode_Id");

                    b.HasIndex("Project_Id");

                    b.HasIndex("ReportType_Id");

                    b.HasIndex("ResultType_Id");

                    b.HasIndex("VIN_Id");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndImportAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfRecords")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Project_Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartImportAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Project_Id");

                    b.HasIndex("Name", "Hash")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Models");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.OperationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OperationCodes");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.ReportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReportTypes");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.ResultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResultTypes");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.VIN", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("VINs");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.DataSet", b =>
                {
                    b.HasOne("QualityControl.WPF.DB.Models.Category", "Category")
                        .WithMany("DataSets")
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.File", "File")
                        .WithMany("DataSets")
                        .HasForeignKey("File_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.License", "License")
                        .WithMany("DataSets")
                        .HasForeignKey("License_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.Model", "Model")
                        .WithMany("DataSets")
                        .HasForeignKey("Model_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.OperationCode", "OperationCode")
                        .WithMany("DataSets")
                        .HasForeignKey("OperationCode_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.Project", "Project")
                        .WithMany("DataSets")
                        .HasForeignKey("Project_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.ReportType", "ReportType")
                        .WithMany("DataSets")
                        .HasForeignKey("ReportType_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.ResultType", "ResultType")
                        .WithMany("DataSets")
                        .HasForeignKey("ResultType_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QualityControl.WPF.DB.Models.VIN", "VIN")
                        .WithMany("DataSets")
                        .HasForeignKey("VIN_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("File");

                    b.Navigation("License");

                    b.Navigation("Model");

                    b.Navigation("OperationCode");

                    b.Navigation("Project");

                    b.Navigation("ReportType");

                    b.Navigation("ResultType");

                    b.Navigation("VIN");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.File", b =>
                {
                    b.HasOne("QualityControl.WPF.DB.Models.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("Project_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.Category", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.File", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.License", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.Model", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.OperationCode", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.Project", b =>
                {
                    b.Navigation("DataSets");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.ReportType", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.ResultType", b =>
                {
                    b.Navigation("DataSets");
                });

            modelBuilder.Entity("QualityControl.WPF.DB.Models.VIN", b =>
                {
                    b.Navigation("DataSets");
                });
#pragma warning restore 612, 618
        }
    }
}
