<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <PackageIcon>icons8-dashboard-100.png</PackageIcon>
    <ApplicationIcon>icons8-dashboard-100.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icons8-dashboard-100.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icons8-dashboard-100.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="EFCore.BulkExtensions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.16" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.10" />
    <PackageReference Include="TypeGen" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icons8-dashboard-100.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="dashboard-64.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
